import type { Metadata } from "next";

import "./globals.css";
import { Inter, Merriweather } from 'next/font/google';
import BackToTopButton from "./components/BackToTopButton";
import { Toaster } from 'sonner'

const inter = Inter({ subsets: ['latin'] });
const merriweather = Merriweather({ subsets: ['latin'], weight: ['300','400', '700',] });


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${merriweather.className} antialiased`}
      >
        <Toaster richColors position="top-center" />
        {children}
        <BackToTopButton />
      </body>
    </html>
  );
}
